=== EduardoArc3/Esquemas_de_XML/src/TareaXML_DTD/Song.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Mr.Music">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cancion" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Titulo" type="xs:string"/>
                            <xs:element name="Compositores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Compositor">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Nombres" type="xs:string"/>
                                                    <xs:element name="Apellidos" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Productores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Productor">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Nombres" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Sello" type="xs:string"/>
                            <xs:element name="Artista" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="anio" type="xs:integer" use="required"/>
                        <xs:attribute name="duracion" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== EduardoArc3/Esquemas_de_XML/src/TareaXML_DTD/Song.xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<Mr.Music xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Song.xsd">
  <cancion anio="1975" duracion="6:00">
    <Titulo>Bohemian Rhapsody</Titulo>
    <Compositores>
      <Compositor>
        <Nombres>Freddy</Nombres>
        <Apellidos>Mercury</Apellidos>
      </Compositor>
    </Compositores>
    <Productores>
      <Productor>
        <Nombres>Reinhold Mack</Nombres>
      </Productor>
    </Productores>
    <Sello>EMI Records</Sello>
    <Artista>Queen</Artista>
  </cancion>
  <cancion anio="2012" duracion="4:55">
    <Titulo>Maquiavélico</Titulo>
    <Compositores>
      <Compositor>
        <Nombres>Tirone José</Nombres>
        <Apellidos>González Orama</Apellidos>
      </Compositor>
    </Compositores>
    <Productores>
      <Productor>
        <Nombres>Kpú</Nombres>
      </Productor>
    </Productores>
    <Sello>Independiente</Sello>
    <Artista>Canserbero</Artista>
  </cancion>
  <cancion anio="1974" duracion="3:12">
    <Titulo>Killer Queen</Titulo>
    <Compositores>
      <Compositor>
        <Nombres>Freddy</Nombres>
        <Apellidos>Mercury</Apellidos>
      </Compositor>
    </Compositores>
    <Productores>
      <Productor>
        <Nombres>Reinhold Mack</Nombres>
      </Productor>
    </Productores>
    <Sello>Parlophone</Sello>
    <Artista>Queen</Artista>
  </cancion>
</Mr.Music>
